export enum UserConstants {
  USER_GET_ALL_START = 'USER_GET_ALL_START',
  USER_GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS',
  USER_GET_ALL_FAIL = 'USER_GET_ALL_FAIL',
  USER_GET_BY_LOGIN_START = 'USER_GET_BY_LOGIN_START',
  USER_GET_BY_LOGIN_SUCCESS = 'USER_GET_BY_LOGIN_SUCCESS',
  USER_GET_BY_LOGIN_FAIL = 'USER_GET_BY_LOGIN_FAIL',
}
